first_name=input("Enter your first name: ")
last_name=input("Enter your last name: ")
full_name=first_name+" "+last_name
print()
country=input("Enter country: ")
city=input("Enter the city name: ")
year=input("Enter the year: ")
print()
print("Full name:", full_name)
print()
print("Address: ", country,city,year,sep="\n\t\t")
print()

is_true=input("whether true or not: ")
print(is_true=="true")
is_light_on=input("Type whether the light on or off: ")
print("The light is", is_light_on)
a,b,c=input("Enter value a: "),input("Enter value b: "), input("Enter value c; ")
print(a,b,c,sep="\n")
first_name=input("Enter the first name: ")
last_name=input("Enter the last name: ")
country=input("Enter the country name: ")
age=int(input("Enter the age: "))
print(first_name,last_name,country,age,sep="\n")

